title: Ombre e Percorsi
description: Tracce di luoghi, storie e persone
baseurl: "" 
url: "https://pietro00b.github.io"

# Impostazioni standard Jekyll
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Esclusioni
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
