# Informazioni del sito
title: "Ombre e Percorsi"
description: "Tracce di luoghi, storie e persone"
baseurl: "/ombre-e-percorsi"
url: "https://pietro00b.github.io"

# Autore
author:
  name: "Pietro"
  email: "pbarale00@gmail.com"
  bio: "Racconto luoghi, storie e incontri attraverso parole e immagini."

# Social media
social:
  github: "pietro00b"
  email: "pbarale00@gmail.com"

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:year/:month/:day/:title/
timezone: Europe/Rome
lang: it

# Paginazione 
paginate: 6
paginate_path: "/pagina:num/"

# Plugin (solo quelli supportati da GitHub Pages)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-paginate

# Menu di navigazione
navigation:
  - title: "Home"
    url: "/"
  - title: "Archivio"
    url: "/archivio/"
  - title: "Galleria"
    url: "/galleria/"
  - title: "Chi sono"
    url: "/about/"

# Esclusioni
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/
  - "*.gem"
  - "*.gemspec"

# Inclusioni per le pagine in cartella pages
include:
  - pages

# Configurazioni Jekyll per GitHub Pages
safe: true
incremental: false

# Sass
sass:
  sass_dir: _sass
  style: compressed

# SEO e defaults
defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      comments: false
      share: true
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "pages"
    values:
      layout: "page"
